name: pluto_grid
description: PlutoGrid is a dataGrid that can be controlled by the keyboard on desktop and web. Of course, it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table, Sticky)
version: 7.0.2
homepage: https://pluto.weblaze.dev
repository: https://github.com/bosskmk/pluto_grid

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  rxdart: ^0.28.0
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
